import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-40">
        <div className="text-center">
          <div className="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
            Contact List Tracker
          </div>
          <div className="mt-6 text-lg leading-8 text-gray-600">
            Never Lost Anyone
          </div>
        </div>
        <div className="mt-10 flex items-center justify-center gap-x-6">
          <a
            href="/auth/login"
            className="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            Login
          </a>
          <a
            href="/auth/signup"
            className="text-sm font-semibold leading-6 text-gray-900"
          >
            Sign up <span aria-hidden="true">→</span>
          </a>
        </div>
      </div>
    </>
  );
}
